### ISSUE TITLE
Add Calypso preset

### ISSUE THREAD

**Issue by ntwb** [WordPress-Coding-Standards/stylelint-config-wordpress#108]
References:

• https://developer.wordpress.com/calypso/

• https://wpcalypso.wordpress.com/devdocs/docs/coding-guidelines/css.md

• https://github.com/Automattic/wp-calypso/blob/master/.stylelintrc

• https://github.com/Automattic/wp-calypso/pull/6356

**Comment by timelsass** [comment]
First, thanks for making this in the first place, it's been a great asset!

Wouldn't it be more fitting to have the calypso configs as it's own repo? Or if there's a large amount of similarities include the .org rules as a dep and extend the rules, but still in it's own repo?

The fact that .com and .org are separate things with two different sets of rules and guidelines for plugin/theme submissions like the .com VIP standards for PHP - and the internal coding standards for each seems like this wouldn't be the best of fit here.

I'm only asking because I'm genuinely curious as to what your reasons are for wanting to implement them here as a preset to select from.  I trust your judgement on this as a stylelint team member and of course a long time wp contributor, author and more.  I don't have any use cases in my workflow that would require me to explicitly check each.  I haven't looked at the calypso rules, but imagine adding a preset is called for because there are different standards.  I have some shared CSS between repos where I do have two sets of standards that they apply to, but I handle this by linting the build and running my fixes for the build results.  I also don't think that my use case is going to be very common for people who would most use this repo, and even more so less common for people working on shared code justifying two sets of standards for .com/.org - but I could be wrong on that.

I've made a couple of postcss plugins publicly available in hopes to contribute back to getting stylefmt able to take care of this config's lint fixes and ditch my own convoluted auto-fix after I run your lints, so I'd strive to say I'm a daily user of this particular repo.  I also embrace the philosophy of each WordPress and PostCSS plugin communities' guidelines of "Do one thing, and do it well."  This feels like it might blur that line a bit, even if it's on the tiniest micro scale imaginable.  Just wanna know your thoughts on this !  Thanks again for all your contributions!

**Comment by ntwb** [comment]
> First, thanks for making this in the first place, it's been a great asset!

Thanks 😄 

> Wouldn't it be more fitting to have the calypso configs as it's own repo? Or if there's a large amount of similarities include the .org rules as a dep and extend the rules, but still in it's own repo?
> 
> The fact that .com and .org are separate things with two different sets of rules and guidelines for plugin/theme submissions like the .com VIP standards for PHP - and the internal coding standards for each seems like this wouldn't be the best of fit here.

Indeed .com VIP and .org are completely separate and I've no plans on adding a VIP stylelint preset to this repo. The distinction I want to make here is .com's VIP is not the same as Calypso, Calypso as an open source project that is related to both .com and .org via Jetpack, more on this below.

> I'm only asking because I'm genuinely curious as to what your reasons are for wanting to implement them here as a preset to select from. I trust your judgement on this as a stylelint team member and of course a long time wp contributor, author and more. I don't have any use cases in my workflow that would require me to explicitly check each. I haven't looked at the calypso rules, but imagine adding a preset is called for because there are different standards. I have some shared CSS between repos where I do have two sets of standards that they apply to, but I handle this by linting the build and running my fixes for the build results. I also don't think that my use case is going to be very common for people who would most use this repo, and even more so less common for people working on shared code justifying two sets of standards for .com/.org - but I could be wrong on that.

Calypso now allows plugins, albeit currently limited to the "Top" plugins, to integrate with Calypso:

>> Via https://wptavern.com/state-of-the-word-2016-mullenweg-pushes-calypso-as-future-of-wordpress-interface-proposes-major-changes-to-release-cycle
>> 
>> _"If Calypso has a chance at becoming a promising replacement for the WordPress admin, its creators will need to broaden its interoperability with the WordPress plugin ecosystem. Mullenweg announced that Calypso is now plugin aware and is open to plugins with over 1M active sites."_
>> 
>> _"The next step on Calypso’s roadmap is to bring in support for Automattic’s plugins – WooCommerce, Akismet, Jetpack, and VaultPress. Mullenweg said the big focus for 2017 is to make plugins Calypso-aware, starting with a handful of the most popular ones before opening it up to all plugins."_

So this is the reason I thought a Calypso preset would be most beneficial, it would allow the plugin authors to continue to use a single stylelint configuration that adheres to WordPress' Coding Standards, but also can be used to apply the Calypso rules for CSS that would need to be included with Calypso.

So that's the theory of why I originally created this issue to address the above, or I should say, that's currently how I see it in my head, practically it might not work and would be best as a separate module, i.e. `stylelint-config-calypso`, time will tell I guess.

> I've made a couple of postcss plugins publicly available in hopes to contribute back to getting stylefmt able to take care of this config's lint fixes and ditch my own convoluted auto-fix after I run your lints, so I'd strive to say I'm a daily user of this particular repo. I also embrace the philosophy of each WordPress and PostCSS plugin communities' guidelines of "Do one thing, and do it well." This feels like it might blur that line a bit, even if it's on the tiniest micro scale imaginable. Just wanna know your thoughts on this ! Thanks again for all your contributions!

For sure, it's definitely a little blurry, I also think Calypso is a little blurry in a similar manner, Calypso is not just a .com product, it will be both a .com and a .org product.
