### ISSUE TITLE
Create new release to ship latest changes

### ISSUE THREAD

**Issue by luminuu** [WordPress-Coding-Standards/stylelint-config-wordpress#268]
A month ago, changes were made to update deprecated rule names: https://github.com/WordPress-Coding-Standards/stylelint-config-wordpress/commit/7816e565b44cdb16969297f967343f6c8b092be6

Since no new release was created so far, we're still getting errors when using this package, for example: https://github.com/WordPress/twentytwentyone/issues/188

I also get this warning on another project I'm working on.

Is it possible to create a new release to remove these warnings?

**Comment by luminuu** [comment]
Ping @ntwb - can you have a look on this? 🙂

**Comment by dero** [comment]
Hey! Any chance a new release could be created and published to fix this annoying issue, please?

**Comment by rodrigo-arias** [comment]
I mentioned the same here #266 without luck for now.

**Comment by ocean90** [comment]
The config has been [migrated](https://github.com/WordPress/gutenberg/pull/22777) to [`@wordpress/stylelint-config`](https://github.com/WordPress/gutenberg/tree/master/packages/stylelint-config) though here's no npm release yet. Once the release is done you can switch to `@wordpress/stylelint-config` which includes the fix for the warning.

**Comment by ocean90** [comment]
[@wordpress/stylelint-config](https://www.npmjs.com/package/@wordpress/stylelint-config) is now available.

**Comment by rodrigo-arias** [comment]
@ocean90 I think the version published in NPM is not up to date. I can see the update in the master branch but not in the one tagged 18.0.0 which I suspect is the one that was published because it is what I get with NPM.

https://github.com/WordPress/gutenberg/blob/master/packages/stylelint-config/index.js#L44
vs.
https://github.com/WordPress/gutenberg/blob/%40wordpress/stylelint-config%4018.0.0/packages/stylelint-config/index.js#L44

**Comment by sladomic** [comment]
Shouldn't the migration be mentioned in the README?

**Comment by ntwb** [comment]
Thanks @ocean90, closing this and apologies for not being available earlier to do this
